# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

[[override]]
  name = "github.com/libopenstorage/gossip"
  branch = "logrus"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.8"

[[constraint]]
  name = "k8s.io/client-go"
  version = "v5.0.0"

[[constraint]]
  name = "github.com/libopenstorage/openstorage"
  branch = "sirupsen-lowercase"

[[constraint]]
  name = "github.com/portworx/sched-ops"
  branch = "master"

[[override]]
  name = "github.com/coreos/bbolt"
  version = "v1.3.1-coreos.6"

[prune]
  go-tests = true
  unused-packages = true
